<a href="https://colab.research.google.com/github/nicole-kutswa/Nairobi-real-estate-analysis/blob/main/Nairobi_real_estate_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [107]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [108]:
pd.set_option("display.max_columns", None)
sns.set_style("whitegrid")

In [109]:
path= '/content/drive/MyDrive/Projects/Nairobi real estate analysis/Nairobi propertyprices - Sheet1.csv'

In [110]:
df= pd.read_csv(path)

In [111]:
df.head()

,Price,propertyType,Location,Bedroom,bathroom,House size,Land size
0,KSh 350 000 000,Townhouse,Runda,4.0,4.0,NaN,0.5 acres
1,KSh 30 000 000,Vacant Land,Karen,NaN,NaN,NaN,0.5 acres
2,KSh 325 000 000,Vacant Land,Westlands,NaN,NaN,NaN,0.5 acres
3,KSh 80 000 000,Townhouse,Kitisuru,5.0,5.0,NaN,0.5 acres
4,KSh 25 500 000,Apartment,Kileleshwa,4.0,4.0,230 m²,NaN

In [112]:
df.shape

(204, 7)

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Price         204 non-null    object
 1   propertyType  204 non-null    object
 2   Location      204 non-null    object
 3   Bedroom       183 non-null    float64
 4   bathroom      181 non-null    float64
 5   House size    99 non-null     object
 6   Land size     64 non-null     object
dtypes: float64(2), object(5)
memory usage: 11.3+ KB

In [114]:
df.describe(include= "all")

,Price,propertyType,Location,Bedroom,bathroom,House size,Land size
count,204,204,204,183.000000,181.000000,99,64
unique,98,6,26,NaN,NaN,54,13
top,KSh 16 000 000,Apartment,Kilimani,NaN,NaN,150 m²,0.5 acres
freq,9,104,37,NaN,NaN,7,37
mean,NaN,NaN,NaN,3.513661,2.906077,NaN,NaN
std,NaN,NaN,NaN,1.585851,1.628570,NaN,NaN
min,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN
25%,NaN,NaN,NaN,2.000000,2.000000,NaN,NaN
50%,NaN,NaN,NaN,4.000000,2.000000,NaN,NaN
75%,NaN,NaN,NaN,5.000000,4.000000,NaN,NaN
max,NaN,NaN,NaN,8.000000,8.000000,NaN,NaN

In [115]:
df= df.rename(columns = {'Price': 'price', 'propertyType': 'property_type', 'Location': 'location', 'Bedroom': 'bedroom', 'House size': 'house_size', 'Land size': 'land_size'})

In [116]:
df.columns

Index(['price', 'property_type', 'location', 'bedroom', 'bathroom',
       'house_size', 'land_size'],
      dtype='object')

In [117]:
df= (
    df
    .assign(
        price = lambda x: x['price'].str.replace("KSh", "", regex= False)
        .str.replace("Ksh", "", regex= False)
        .str.replace(" ", "", regex= False)
        .str.strip()
        .astype(float)
        ,
        house_size= lambda x: x['house_size'].str.replace("m²", "", regex= False)
        .str.replace(" ", "", regex= False)
        .str.replace('"', "", regex= False)
        .str.replace("acres", "", regex= False)
        .astype(float)
        ,
        land_size= lambda x: x['land_size'].str.replace('acres', "", regex= False)
        .astype(float)
    )
)

In [118]:
df.describe(include= "all")

,price,property_type,location,bedroom,bathroom,house_size,land_size
count,2.040000e+02,204,204,183.000000,181.000000,99.000000,64.000000
unique,NaN,6,26,NaN,NaN,NaN,NaN
top,NaN,Apartment,Kilimani,NaN,NaN,NaN,NaN
freq,NaN,104,37,NaN,NaN,NaN,NaN
mean,8.638380e+07,NaN,NaN,3.513661,2.906077,199.171717,0.880469
std,1.270899e+08,NaN,NaN,1.585851,1.628570,228.605535,1.312929
min,3.500000e+06,NaN,NaN,1.000000,1.000000,1.000000,0.120000
25%,1.450000e+07,NaN,NaN,2.000000,2.000000,90.000000,0.500000
50%,3.000000e+07,NaN,NaN,4.000000,2.000000,150.000000,0.500000
75%,1.150000e+08,NaN,NaN,5.000000,4.000000,226.500000,0.750000
max,9.480000e+08,NaN,NaN,8.000000,8.000000,2025.000000,7.900000

In [119]:
df.isnull().sum()

price              0
property_type      0
location           0
bedroom           21
bathroom          23
house_size       105
land_size        140
dtype: int64

In [120]:
df.duplicated().sum()

np.int64(32)

In [121]:
df= df.drop_duplicates()

In [122]:
df.duplicated().sum()

np.int64(0)

In [123]:
df.shape

(172, 7)

In [128]:
df= (
    df
    .assign(
        bedroom= df.groupby('property_type')['bedroom'].transform(lambda x: x.fillna(x.median())),
        bathroom= df.groupby('property_type')['bathroom'].transform(lambda x: x.fillna(x.median())),
    )
)

In [129]:
df['bedroom'].isnull().sum()

np.int64(17)